package handlers

import (
	"bytes"
	"context"
	"encoding/csv"
	"fmt"
	"io"
	"net/http"
	"strconv"
	"strings"

	"goodpack-server/models"
	"goodpack-server/repository"
	"goodpack-server/utils"

	"go.mongodb.org/mongo-driver/bson/primitive"
	"golang.org/x/text/encoding/unicode"
	"golang.org/x/text/transform"
)

type ImportHandler struct {
	customerRepo *repository.CustomerRepository
	productRepo  *repository.ProductRepository
}

func NewImportHandler(customerRepo *repository.CustomerRepository, productRepo *repository.ProductRepository) *ImportHandler {
	return &ImportHandler{
		customerRepo: customerRepo,
		productRepo:  productRepo,
	}
}

// ImportCustomers handles CSV import for customers
// POST /api/import/customers
// Input CSV: old_id,company_name,contact_name,tax_id,phone,address,contact_method
// Output CSV: old_id,new_id,new_customer_code,company_name,status,error
func (h *ImportHandler) ImportCustomers(w http.ResponseWriter, r *http.Request) {
	// Parse multipart form (max 10MB)
	if err := r.ParseMultipartForm(10 << 20); err != nil {
		http.Error(w, "Failed to parse form: "+err.Error(), http.StatusBadRequest)
		return
	}

	// Get uploaded file
	file, _, err := r.FormFile("file")
	if err != nil {
		http.Error(w, "Failed to get file: "+err.Error(), http.StatusBadRequest)
		return
	}
	defer file.Close()

	// Convert to UTF-8 reader for proper Thai character support
	utf8Reader := transform.NewReader(file, unicode.UTF8BOM.NewDecoder())

	// Read CSV
	reader := csv.NewReader(utf8Reader)
	
	// Read header
	header, err := reader.Read()
	if err != nil {
		http.Error(w, "Failed to read CSV header: "+err.Error(), http.StatusBadRequest)
		return
	}

	// Validate header
	expectedHeader := []string{"old_id", "company_name", "contact_name", "tax_id", "phone", "address", "contact_method"}
	if !validateHeader(header, expectedHeader) {
		http.Error(w, fmt.Sprintf("Invalid CSV header. Expected: %v", expectedHeader), http.StatusBadRequest)
		return
	}

	// Prepare result CSV
	var resultBuffer bytes.Buffer
	resultWriter := csv.NewWriter(&resultBuffer)
	resultWriter.Write([]string{"old_id", "new_id", "new_customer_code", "company_name", "status", "error"})

	// Process each row
	lineNum := 1
	successCount := 0
	failCount := 0

	for {
		record, err := reader.Read()
		if err == io.EOF {
			break
		}
		lineNum++

		if err != nil {
			resultWriter.Write([]string{"", "", "", "", "failed", fmt.Sprintf("Line %d: %v", lineNum, err)})
			failCount++
			continue
		}

		// Parse row
		if len(record) < 7 {
			// Pad with empty strings
			for len(record) < 7 {
				record = append(record, "")
			}
		}

		oldID := strings.TrimSpace(record[0])
		companyName := strings.TrimSpace(record[1])
		contactName := strings.TrimSpace(record[2])
		taxID := strings.TrimSpace(record[3])
		phone := strings.TrimSpace(record[4])
		address := strings.TrimSpace(record[5])
		contactMethod := strings.TrimSpace(record[6])

		// Validate required fields
		if companyName == "" {
			resultWriter.Write([]string{oldID, "", "", companyName, "failed", "company_name is required"})
			failCount++
			continue
		}

		// Create customer (CustomerCode will be generated by repository)
		customer := &models.Customer{
			CompanyName:   companyName,
			ContactName:   contactName,
			TaxID:         taxID,
			Phone:         phone,
			Address:       address,
			ContactMethod: contactMethod,
			CreatedAt:     utils.NowInThailand(),
			UpdatedAt:     utils.NowInThailand(),
		}

		// Save to database (repository generates CustomerCode automatically)
		if err := h.customerRepo.Create(customer); err != nil {
			resultWriter.Write([]string{oldID, "", "", companyName, "failed", "Failed to create: " + err.Error()})
			failCount++
			continue
		}

		// Success
		resultWriter.Write([]string{oldID, customer.ID.Hex(), customer.CustomerCode, companyName, "success", ""})
		successCount++
	}

	resultWriter.Flush()

	// Set response headers
	w.Header().Set("Content-Type", "text/csv")
	w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=customers_result_%s.csv", utils.NowInThailand().Format("20060102_150405")))
	w.Header().Set("X-Import-Success", strconv.Itoa(successCount))
	w.Header().Set("X-Import-Failed", strconv.Itoa(failCount))
	w.Header().Set("X-Import-Total", strconv.Itoa(successCount+failCount))
	// Expose custom headers for CORS
	w.Header().Set("Access-Control-Expose-Headers", "X-Import-Success, X-Import-Failed, X-Import-Total")

	// Write BOM for Excel UTF-8 support
	w.Write([]byte{0xEF, 0xBB, 0xBF})
	w.Write(resultBuffer.Bytes())
}

// ImportProducts handles CSV import for products
// POST /api/import/products
// Input CSV: old_id,name,description,color,size,category,initial_stock_vat,initial_stock_nonvat,initial_actual_stock
// Output CSV: old_id,new_id,new_sku_id,new_code,name,status,error
func (h *ImportHandler) ImportProducts(w http.ResponseWriter, r *http.Request) {
	ctx := context.Background()

	// Parse multipart form (max 10MB)
	if err := r.ParseMultipartForm(10 << 20); err != nil {
		http.Error(w, "Failed to parse form: "+err.Error(), http.StatusBadRequest)
		return
	}

	// Get uploaded file
	file, _, err := r.FormFile("file")
	if err != nil {
		http.Error(w, "Failed to get file: "+err.Error(), http.StatusBadRequest)
		return
	}
	defer file.Close()

	// Convert to UTF-8 reader for proper Thai character support
	utf8Reader := transform.NewReader(file, unicode.UTF8BOM.NewDecoder())

	// Read CSV
	reader := csv.NewReader(utf8Reader)

	// Read header
	header, err := reader.Read()
	if err != nil {
		http.Error(w, "Failed to read CSV header: "+err.Error(), http.StatusBadRequest)
		return
	}

	// Validate header
	expectedHeader := []string{"old_id", "name", "description", "color", "size", "category", "initial_stock_vat", "initial_stock_nonvat", "initial_actual_stock"}
	if !validateHeader(header, expectedHeader) {
		http.Error(w, fmt.Sprintf("Invalid CSV header. Expected: %v", expectedHeader), http.StatusBadRequest)
		return
	}

	// Prepare result CSV
	var resultBuffer bytes.Buffer
	resultWriter := csv.NewWriter(&resultBuffer)
	resultWriter.Write([]string{"old_id", "new_id", "new_sku_id", "new_code", "name", "status", "error"})

	// Process each row
	lineNum := 1
	successCount := 0
	failCount := 0

	for {
		record, err := reader.Read()
		if err == io.EOF {
			break
		}
		lineNum++

		if err != nil {
			resultWriter.Write([]string{"", "", "", "", "", "failed", fmt.Sprintf("Line %d: %v", lineNum, err)})
			failCount++
			continue
		}

		// Parse row
		if len(record) < 9 {
			// Pad with empty strings
			for len(record) < 9 {
				record = append(record, "")
			}
		}

		oldID := strings.TrimSpace(record[0])
		name := strings.TrimSpace(record[1])
		description := strings.TrimSpace(record[2])
		color := strings.TrimSpace(record[3])
		size := strings.TrimSpace(record[4])
		category := strings.TrimSpace(record[5])
		initialStockVATStr := strings.TrimSpace(record[6])
		initialStockNonVATStr := strings.TrimSpace(record[7])
		initialActualStockStr := strings.TrimSpace(record[8])

		// Parse stock values
		initialStockVAT := 0
		initialStockNonVAT := 0
		initialActualStock := 0

		if initialStockVATStr != "" {
			if val, err := strconv.Atoi(initialStockVATStr); err == nil {
				initialStockVAT = val
			}
		}
		if initialStockNonVATStr != "" {
			if val, err := strconv.Atoi(initialStockNonVATStr); err == nil {
				initialStockNonVAT = val
			}
		}
		if initialActualStockStr != "" {
			if val, err := strconv.Atoi(initialActualStockStr); err == nil {
				initialActualStock = val
			}
		}

		// Validate required fields
		if name == "" {
			resultWriter.Write([]string{oldID, "", "", "", name, "failed", "name is required"})
			failCount++
			continue
		}
		if category == "" {
			resultWriter.Write([]string{oldID, "", "", "", name, "failed", "category is required"})
			failCount++
			continue
		}

		// Create product (SKUID and Code will be generated by repository)
		product := &models.Product{
			ID:          primitive.NewObjectID(),
			Name:        name,
			Description: description,
			Color:       color,
			Size:        normalizeSize(size), // Normalize size (50ml. -> 50 mL)
			Category:    category,
			Price: models.Price{
				PurchaseVAT:    models.PriceInfo{},
				PurchaseNonVAT: models.PriceInfo{},
				SaleVAT:        models.PriceInfo{},
				SaleNonVAT:     models.PriceInfo{},
				SalesTiers:     []models.TierPrice{},
			},
			Stock: models.Stock{
				VAT: models.StockInfo{
					Purchased:    0,
					Sold:         0,
					Remaining:    initialStockVAT,
					InitialStock: initialStockVAT,
				},
				NonVAT: models.StockInfo{
					Purchased:    0,
					Sold:         0,
					Remaining:    initialStockNonVAT,
					InitialStock: initialStockNonVAT,
				},
				ActualStock:        initialActualStock,
				ActualStockInitial: initialActualStock,
			},
			CreatedAt: utils.NowInThailand(),
			UpdatedAt: utils.NowInThailand(),
		}

		// Save to database (repository generates SKUID and Code automatically)
		if err := h.productRepo.Create(ctx, product); err != nil {
			resultWriter.Write([]string{oldID, "", "", "", name, "failed", "Failed to create: " + err.Error()})
			failCount++
			continue
		}

		// Success
		resultWriter.Write([]string{oldID, product.ID.Hex(), product.SKUID, product.Code, name, "success", ""})
		successCount++
	}

	resultWriter.Flush()

	// Set response headers
	w.Header().Set("Content-Type", "text/csv")
	w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=products_result_%s.csv", utils.NowInThailand().Format("20060102_150405")))
	w.Header().Set("X-Import-Success", strconv.Itoa(successCount))
	w.Header().Set("X-Import-Failed", strconv.Itoa(failCount))
	w.Header().Set("X-Import-Total", strconv.Itoa(successCount+failCount))
	// Expose custom headers for CORS
	w.Header().Set("Access-Control-Expose-Headers", "X-Import-Success, X-Import-Failed, X-Import-Total")

	// Write BOM for Excel UTF-8 support
	w.Write([]byte{0xEF, 0xBB, 0xBF})
	w.Write(resultBuffer.Bytes())
}

// Helper functions

func validateHeader(actual, expected []string) bool {
	if len(actual) < len(expected) {
		return false
	}
	for i, exp := range expected {
		// Clean header values (remove BOM, trim spaces)
		actualVal := strings.TrimSpace(strings.TrimPrefix(actual[i], "\ufeff"))
		if !strings.EqualFold(actualVal, exp) {
			return false
		}
	}
	return true
}

func generateProductCode(skuID, color string) string {
	// Get color abbreviation
	colorAbbr := getColorAbbreviation(color)
	if colorAbbr == "" {
		return skuID
	}
	return skuID + "/" + colorAbbr
}

// normalizeSize normalizes size format (50ml. -> 50 mL)
func normalizeSize(size string) string {
	size = strings.TrimSpace(size)
	if size == "" {
		return size
	}

	// Remove trailing dots
	size = strings.TrimSuffix(size, ".")

	// Normalize ml/mL
	size = strings.ReplaceAll(size, "ml", " mL")
	size = strings.ReplaceAll(size, "ML", " mL")
	size = strings.ReplaceAll(size, "Ml", " mL")

	// Normalize L/l (liters)
	if strings.HasSuffix(strings.ToLower(size), "l") && !strings.HasSuffix(size, "mL") {
		size = strings.TrimSuffix(size, "l")
		size = strings.TrimSuffix(size, "L")
		size = strings.TrimSpace(size) + " L"
	}

	// Remove extra spaces
	for strings.Contains(size, "  ") {
		size = strings.ReplaceAll(size, "  ", " ")
	}

	return strings.TrimSpace(size)
}

func getColorAbbreviation(color string) string {
	colorLower := strings.ToLower(strings.TrimSpace(color))
	
	colorMap := map[string]string{
		"น้ำตาล":    "BR",
		"brown":     "BR",
		"ขาว":       "WH",
		"white":     "WH",
		"ดำ":        "BK",
		"black":     "BK",
		"แดง":       "RD",
		"red":       "RD",
		"เขียว":     "GR",
		"green":     "GR",
		"น้ำเงิน":   "BL",
		"blue":      "BL",
		"เหลือง":    "YL",
		"yellow":    "YL",
		"ส้ม":       "OR",
		"orange":    "OR",
		"ชมพู":      "PK",
		"pink":      "PK",
		"ม่วง":      "PP",
		"purple":    "PP",
		"เทา":       "GY",
		"gray":      "GY",
		"grey":      "GY",
		"ใส":        "CL",
		"clear":     "CL",
		"transparent": "CL",
	}

	if abbr, ok := colorMap[colorLower]; ok {
		return abbr
	}
	
	// If not found, use first 2 characters
	if len(color) >= 2 {
		return strings.ToUpper(color[:2])
	}
	return ""
}

// GetImportTemplate returns a sample CSV template
func (h *ImportHandler) GetCustomerTemplate(w http.ResponseWriter, r *http.Request) {
	var buffer bytes.Buffer
	writer := csv.NewWriter(&buffer)
	
	// Header
	writer.Write([]string{"old_id", "company_name", "contact_name", "tax_id", "phone", "address", "contact_method"})
	
	// Sample rows
	writer.Write([]string{"OLD-001", "บริษัท ตัวอย่าง จำกัด", "คุณสมชาย", "0123456789012", "0812345678", "123 ถนนสุขุมวิท กรุงเทพ 10110", "LINE"})
	writer.Write([]string{"OLD-002", "ร้านค้า XYZ", "คุณสมหญิง", "", "0898765432", "456 ถนนพหลโยธิน กรุงเทพ", "โทรศัพท์"})
	
	writer.Flush()

	w.Header().Set("Content-Type", "text/csv; charset=utf-8")
	w.Header().Set("Content-Disposition", "attachment; filename=customers_template.csv")
	
	// Add BOM for Excel UTF-8 support
	w.Write([]byte{0xEF, 0xBB, 0xBF})
	w.Write(buffer.Bytes())
}

func (h *ImportHandler) GetProductTemplate(w http.ResponseWriter, r *http.Request) {
	var buffer bytes.Buffer
	writer := csv.NewWriter(&buffer)
	
	// Header
	writer.Write([]string{"old_id", "name", "description", "color", "size", "category", "initial_stock_vat", "initial_stock_nonvat", "initial_actual_stock"})
	
	// Sample rows
	writer.Write([]string{"OLD-P001", "ถุงกระดาษ A4", "ถุงกระดาษสีน้ำตาล", "น้ำตาล", "A4", "ถุงกระดาษ", "100", "50", "150"})
	writer.Write([]string{"OLD-P002", "กล่องพัสดุ S", "กล่องพัสดุไซส์ S", "น้ำตาล", "S", "กล่อง", "200", "0", "200"})
	
	writer.Flush()

	w.Header().Set("Content-Type", "text/csv; charset=utf-8")
	w.Header().Set("Content-Disposition", "attachment; filename=products_template.csv")
	
	// Add BOM for Excel UTF-8 support
	w.Write([]byte{0xEF, 0xBB, 0xBF})
	w.Write(buffer.Bytes())
}

