package models

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

type Customer struct {
	ID            primitive.ObjectID `bson:"_id,omitempty" json:"id"`
	CustomerCode  string             `bson:"customerCode" json:"customerCode"`
	CompanyName   string             `bson:"companyName" json:"companyName"`
	ContactName   string             `bson:"contactName" json:"contactName"`
	TaxID         string             `bson:"taxId" json:"taxId"`
	Phone         string             `bson:"phone" json:"phone"`
	Address       string             `bson:"address" json:"address"`
	ContactMethod string             `bson:"contactMethod" json:"contactMethod"`
	CreatedAt     time.Time          `bson:"createdAt" json:"createdAt"`
	UpdatedAt     time.Time          `bson:"updatedAt" json:"updatedAt"`
}

type CustomerRequest struct {
	CompanyName   string `json:"companyName" bson:"companyName"`
	ContactName   string `json:"contactName" bson:"contactName"`
	TaxID         string `json:"taxId" bson:"taxId"`
	Phone         string `json:"phone" bson:"phone"`
	Address       string `json:"address" bson:"address"`
	ContactMethod string `json:"contactMethod" bson:"contactMethod"`
}

func (cr *CustomerRequest) ToCustomer() *Customer {
	return &Customer{
		CustomerCode:  "", // Will be generated by server
		CompanyName:   cr.CompanyName,
		ContactName:   cr.ContactName,
		TaxID:         cr.TaxID,
		Phone:         cr.Phone,
		Address:       cr.Address,
		ContactMethod: cr.ContactMethod,
		CreatedAt:     time.Now(),
		UpdatedAt:     time.Now(),
	}
}

func (c *Customer) UpdateFromRequest(cr *CustomerRequest) {
	c.CompanyName = cr.CompanyName
	c.ContactName = cr.ContactName
	c.TaxID = cr.TaxID
	c.Phone = cr.Phone
	c.Address = cr.Address
	c.ContactMethod = cr.ContactMethod
	c.UpdatedAt = time.Now()
}
