package models

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
	"goodpack-server/utils"
)

type Customer struct {
	ID            primitive.ObjectID    `bson:"_id,omitempty" json:"id"`
	CustomerCode  string                `bson:"customerCode" json:"customerCode"`
	CompanyName   string                `bson:"companyName" json:"companyName"`
	ContactName   string                `bson:"contactName" json:"contactName"`     // Legacy: ผู้ติดต่อหลัก (backward compatibility)
	TaxID         string                `bson:"taxId" json:"taxId"`
	Phone         string                `bson:"phone" json:"phone"`                 // Legacy: เบอร์โทรหลัก (backward compatibility)
	Address       string                `bson:"address" json:"address"`
	ContactMethod string                `bson:"contactMethod" json:"contactMethod"`
	Contacts      []Contact             `bson:"contacts" json:"contacts"`           // รายการผู้ติดต่อทั้งหมด
	BankAccounts  []CustomerBankAccount `bson:"bankAccounts" json:"bankAccounts"`   // รายการบัญชีธนาคาร
	CreatedAt     time.Time             `bson:"createdAt" json:"createdAt"`
	UpdatedAt     time.Time             `bson:"updatedAt" json:"updatedAt"`
}

type CustomerRequest struct {
	CompanyName   string                `json:"companyName" bson:"companyName"`
	ContactName   string                `json:"contactName" bson:"contactName"`
	TaxID         string                `json:"taxId" bson:"taxId"`
	Phone         string                `json:"phone" bson:"phone"`
	Address       string                `json:"address" bson:"address"`
	ContactMethod string                `json:"contactMethod" bson:"contactMethod"`
	Contacts      []Contact             `json:"contacts" bson:"contacts"`
	BankAccounts  []CustomerBankAccount `json:"bankAccounts" bson:"bankAccounts"`
}

func (cr *CustomerRequest) ToCustomer() *Customer {
	now := utils.NowInThailand()
	
	// Set default contact from legacy fields if no contacts provided
	contacts := cr.Contacts
	if len(contacts) == 0 && cr.ContactName != "" {
		contacts = []Contact{{
			Name:      cr.ContactName,
			Phone:     cr.Phone,
			IsDefault: true,
		}}
	}
	
	// Get primary contact for legacy fields
	contactName := cr.ContactName
	phone := cr.Phone
	for _, c := range contacts {
		if c.IsDefault {
			contactName = c.Name
			phone = c.Phone
			break
		}
	}
	
	return &Customer{
		CustomerCode:  "", // Will be generated by server
		CompanyName:   cr.CompanyName,
		ContactName:   contactName,
		TaxID:         cr.TaxID,
		Phone:         phone,
		Address:       cr.Address,
		ContactMethod: cr.ContactMethod,
		Contacts:      contacts,
		BankAccounts:  cr.BankAccounts,
		CreatedAt:     now,
		UpdatedAt:     now,
	}
}

func (c *Customer) UpdateFromRequest(cr *CustomerRequest) {
	c.CompanyName = cr.CompanyName
	c.TaxID = cr.TaxID
	c.Address = cr.Address
	c.ContactMethod = cr.ContactMethod
	c.Contacts = cr.Contacts
	c.BankAccounts = cr.BankAccounts
	
	// Update legacy fields from primary contact
	if len(cr.Contacts) > 0 {
		for _, contact := range cr.Contacts {
			if contact.IsDefault {
				c.ContactName = contact.Name
				c.Phone = contact.Phone
				break
			}
		}
		// If no default, use first contact
		if c.ContactName == "" && len(cr.Contacts) > 0 {
			c.ContactName = cr.Contacts[0].Name
			c.Phone = cr.Contacts[0].Phone
		}
	} else {
		c.ContactName = cr.ContactName
		c.Phone = cr.Phone
	}
	
	c.UpdatedAt = utils.NowInThailand()
}
