package models

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
	"goodpack-server/utils"
)

type Supplier struct {
	ID            primitive.ObjectID `bson:"_id,omitempty" json:"id"`
	SupplierCode  string             `bson:"supplierCode" json:"supplierCode"`
	CompanyName   string             `bson:"companyName" json:"companyName"`
	ContactName   string             `bson:"contactName" json:"contactName"`
	TaxID         string             `bson:"taxId" json:"taxId"`
	Phone         string             `bson:"phone" json:"phone"`
	Address       string             `bson:"address" json:"address"`
	ContactMethod string             `bson:"contactMethod" json:"contactMethod"`
	CreatedAt     time.Time          `bson:"createdAt" json:"createdAt"`
	UpdatedAt     time.Time          `bson:"updatedAt" json:"updatedAt"`
}

type SupplierRequest struct {
	CompanyName   string `json:"companyName" bson:"companyName"`
	ContactName   string `json:"contactName" bson:"contactName"`
	TaxID         string `json:"taxId" bson:"taxId"`
	Phone         string `json:"phone" bson:"phone"`
	Address       string `json:"address" bson:"address"`
	ContactMethod string `json:"contactMethod" bson:"contactMethod"`
}

func (sr *SupplierRequest) ToSupplier() *Supplier {
	now := utils.NowInThailand()
	return &Supplier{
		SupplierCode:  "", // Will be generated by server
		CompanyName:   sr.CompanyName,
		ContactName:   sr.ContactName,
		TaxID:         sr.TaxID,
		Phone:         sr.Phone,
		Address:       sr.Address,
		ContactMethod: sr.ContactMethod,
		CreatedAt:     now,
		UpdatedAt:     now,
	}
}

func (s *Supplier) UpdateFromRequest(sr *SupplierRequest) {
	s.CompanyName = sr.CompanyName
	s.ContactName = sr.ContactName
	s.TaxID = sr.TaxID
	s.Phone = sr.Phone
	s.Address = sr.Address
	s.ContactMethod = sr.ContactMethod
	s.UpdatedAt = utils.NowInThailand()
}
