package models

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
	"goodpack-server/utils"
)

type Supplier struct {
	ID            primitive.ObjectID `bson:"_id,omitempty" json:"id"`
	SupplierCode  string             `bson:"supplierCode" json:"supplierCode"`
	CompanyName   string             `bson:"companyName" json:"companyName"`
	ContactName   string             `bson:"contactName" json:"contactName"`     // Legacy: ผู้ติดต่อหลัก (backward compatibility)
	TaxID         string             `bson:"taxId" json:"taxId"`
	Phone         string             `bson:"phone" json:"phone"`                 // Legacy: เบอร์โทรหลัก (backward compatibility)
	Address       string             `bson:"address" json:"address"`
	ContactMethod string             `bson:"contactMethod" json:"contactMethod"`
	Contacts      []Contact          `bson:"contacts" json:"contacts"`           // รายการผู้ติดต่อทั้งหมด
	CreatedAt     time.Time          `bson:"createdAt" json:"createdAt"`
	UpdatedAt     time.Time          `bson:"updatedAt" json:"updatedAt"`
}

type SupplierRequest struct {
	CompanyName   string    `json:"companyName" bson:"companyName"`
	ContactName   string    `json:"contactName" bson:"contactName"`
	TaxID         string    `json:"taxId" bson:"taxId"`
	Phone         string    `json:"phone" bson:"phone"`
	Address       string    `json:"address" bson:"address"`
	ContactMethod string    `json:"contactMethod" bson:"contactMethod"`
	Contacts      []Contact `json:"contacts" bson:"contacts"`
}

func (sr *SupplierRequest) ToSupplier() *Supplier {
	now := utils.NowInThailand()
	
	// Set default contact from legacy fields if no contacts provided
	contacts := sr.Contacts
	if len(contacts) == 0 && sr.ContactName != "" {
		contacts = []Contact{{
			Name:      sr.ContactName,
			Phone:     sr.Phone,
			IsDefault: true,
		}}
	}
	
	// Get primary contact for legacy fields
	contactName := sr.ContactName
	phone := sr.Phone
	for _, c := range contacts {
		if c.IsDefault {
			contactName = c.Name
			phone = c.Phone
			break
		}
	}
	
	return &Supplier{
		SupplierCode:  "", // Will be generated by server
		CompanyName:   sr.CompanyName,
		ContactName:   contactName,
		TaxID:         sr.TaxID,
		Phone:         phone,
		Address:       sr.Address,
		ContactMethod: sr.ContactMethod,
		Contacts:      contacts,
		CreatedAt:     now,
		UpdatedAt:     now,
	}
}

func (s *Supplier) UpdateFromRequest(sr *SupplierRequest) {
	s.CompanyName = sr.CompanyName
	s.TaxID = sr.TaxID
	s.Address = sr.Address
	s.ContactMethod = sr.ContactMethod
	s.Contacts = sr.Contacts
	
	// Update legacy fields from primary contact
	if len(sr.Contacts) > 0 {
		for _, contact := range sr.Contacts {
			if contact.IsDefault {
				s.ContactName = contact.Name
				s.Phone = contact.Phone
				break
			}
		}
		// If no default, use first contact
		if s.ContactName == "" && len(sr.Contacts) > 0 {
			s.ContactName = sr.Contacts[0].Name
			s.Phone = sr.Contacts[0].Phone
		}
	} else {
		s.ContactName = sr.ContactName
		s.Phone = sr.Phone
	}
	
	s.UpdatedAt = utils.NowInThailand()
}
